# Generated by Django 4.2.11 on 2024-03-17 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_workrecord_working_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workrecord",
            name="working_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 17, 15, 56, 10, 836934, tzinfo=datetime.timezone.utc
                ),
                verbose_name="工作日期",
            ),
        ),
    ]
