# Generated by Django 4.2.11 on 2024-03-17 16:29

import datetime
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_workrecord_working_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workrecord",
            name="slug",
            field=django_extensions.db.fields.RandomCharField(
                blank=True,
                editable=False,
                length=32,
                unique=True,
                unique_for_date="working_date",
            ),
        ),
        migrations.AlterField(
            model_name="workrecord",
            name="working_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 17, 16, 29, 49, 656788, tzinfo=datetime.timezone.utc
                ),
                verbose_name="工作日期",
            ),
        ),
    ]
