# Generated by Django 4.2.11 on 2024-03-31 02:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0007_alter_workrecord_working_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workrecord",
            name="slug",
            field=django_extensions.db.fields.RandomCharField(
                blank=True, editable=False, length=32, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="workrecord",
            name="working_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 31, 2, 52, 49, 23549, tzinfo=datetime.timezone.utc
                ),
                verbose_name="工作日期",
            ),
        ),
        migrations.CreateModel(
            name="ToDo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "slug",
                    django_extensions.db.fields.RandomCharField(
                        blank=True,
                        editable=False,
                        length=32,
                        unique=True,
                        unique_for_date=models.DateTimeField(auto_now_add=True),
                    ),
                ),
                ("todo_text", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "todo_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todo_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
