# Generated by Django 4.2.11 on 2024-03-31 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_workrecord_slug_alter_workrecord_working_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={},
        ),
        migrations.RemoveField(
            model_name="todo",
            name="slug",
        ),
        migrations.AlterField(
            model_name="workrecord",
            name="working_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 31, 17, 10, 51, 753110, tzinfo=datetime.timezone.utc
                ),
                verbose_name="工作日期",
            ),
        ),
    ]
