# Generated by Django 5.0.3 on 2024-04-02 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_todo_options_remove_todo_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='working_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 2, 15, 20, 10, 994172, tzinfo=datetime.timezone.utc), verbose_name='工作日期'),
        ),
    ]
