# Generated by Django 5.0.3 on 2024-04-02 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_workrecord_working_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='working_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 2, 16, 34, 24, 968627, tzinfo=datetime.timezone.utc), verbose_name='工作日期'),
        ),
    ]
